# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Prompt
# PROMPT='%F{red}%n@%m %F{blue}%~ %f⚛ '
# PS1='\[\e[1;31m\]\u\[\e[0m\]\[\e[1;35m\]⚛\[\e[0m\]\[\e[1;34m\]\h\[\e[0m\] \[\e[38;5;70m\]\w\]\e[0m\]\$ '
# PS1='\[\e[1;31m\]\u\[\e[0m\]\[\e[1;37m\]⚛\[\e[0m\]\[\e[1;34m\]\h\[\e[0m\] \[\e[38;5;70m\]\w\]\e[0m\]\$ '
source "$HOME/Tools/sh/current.theme"
PS2='... '
PS3='::: '
PS4='+ ${BASH_SOURCE}:${LINENO}: '

# Path
export PATH="$HOME/Tools/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# Python PATHS
export PYTHONPATH="$HOME/Tools/python:$PYTHONPATH"

# Sourcing files
source $HOME/Tools/sh/alias
source $HOME/Tools/sh/analysis
source $HOME/Tools/sh/bash-bindings
source $HOME/Tools/sh/function
[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env

# History
HISTSIZE=1000000
HISTFILESIZE=2000000
HISTCONTROL=ignoreboth
shopt -s histappend
export PROMPT_COMMAND="history -a"
# PROMPT_COMMAND="history -a; history -n"


###############################################################################
# # >>> mamba initialize >>>
# # !! Contents within this block are managed by 'micromamba shell init' !!
# export MAMBA_EXE='/home/r/.local/bin/micromamba';
# export MAMBA_ROOT_PREFIX='/home/r/micromamba';
# __mamba_setup="$("$MAMBA_EXE" shell hook --shell zsh --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__mamba_setup"
# else
#     alias micromamba="$MAMBA_EXE"  # Fallback on help from micromamba activate
# fi
# unset __mamba_setup
# # <<< mamba initialize <<<
# --- pyenv (MUST be early in PATH) ---
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# eval "$(pyenv init --path)"
# eval "$(pyenv init -)"
pyenv() {
    unset -f pyenv
    eval "$(command pyenv init -)"
    pyenv "$@"
}
###############################################################################

# Eval apps
eval "$(zoxide init bash)"

. "$HOME/.cargo/env"

###############################################################################
# --- OpenFOAM  ---
export WM_PROJECT_DIR=/opt/OpenFOAM/OpenFOAM-13
# if [ -f $WM_PROJECT_DIR/etc/bashrc ]; then
#     source $WM_PROJECT_DIR/etc/bashrc
# fi
# use foam to load the foam

# --- openmpi  ---
export PATH=/usr/lib/openmpi/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib/openmpi/lib:$LD_LIBRARY_PATH
###############################################################################
