# ZSH APPS COMPINSTALL
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]} r:|[.]=* r:|=*' 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename '/home/r/.zshrc'
autoload -Uz compinit
compinit
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt extendedglob notify
unsetopt beep
bindkey -v

# source "$HOME/Tools/sh/current.theme"
show_shell_variables() {

}
# PS1="%F{#008000}[%T]<%L>%K{3a3a3a}%n@%m%k %S%1~:(%j)%s "
PROMPT='%F{red}%n⚛%m %f%F{green}%~%f '
PS2='... '
PS3='::: '
PS4='+ ${BASH_SOURCE}:${LINENO}: '
# Prompt
autoload -Uz colors && colors
setopt prompt_subst

# Variables
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="qutebrowser"
export TERMINAL="foot"
export MANPAGER='nvim +Man'
export GPG_TTY=$(tty)

# Path
export PATH="$HOME/Tools/bin:$PATH"
export PATH="/usr/local/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
# Python PATHS
export PYTHONPATH="$HOME/Tools/python:$PYTHONPATH"

# Sourcing files
source $HOME/Tools/sh/alias
source $HOME/Tools/sh/analysis
source $HOME/Tools/sh/function
[ -f $HOME/.cargo/env ] && source $HOME/.cargo/env
# source $HOME/Tools/sh/bash-bindings

# Vim bindkeys
bindkey -M vicmd '^[[1;5D' backward-word
bindkey -M vicmd '^[[1;5C' forward-word
bindkey -M viins '^[[1;5D' backward-word
bindkey -M viins '^[[1;5C' forward-word
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins 'jk' vi-cmd-mode
bindkey -M viins "^[[3~" delete-char
bindkey -M vicmd "^[[3~" delete-char
bindkey -M viins "^[[3;5~" kill-word
bindkey -M vicmd "^[[3;5~" kill-word
bindkey -M viins '^H' backward-kill-word
bindkey -M vicmd '^H' backward-kill-word

export PROMPT_COMMAND="history -a"

###############################################################################
#
# Other Apps
#
###############################################################################

# --- pyenv (MUST be early in PATH) ---
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
pyenv() {
    unset -f pyenv
    eval "$(command pyenv init -)"
    pyenv "$@"
}

# --- Zoxide  ---
eval "$(zoxide init zsh)"
. "$HOME/.cargo/env"

# --- OpenFOAM  ---
export WM_PROJECT_DIR=/opt/OpenFOAM/OpenFOAM-13

# --- openmpi  ---
export PATH=/usr/lib/openmpi/bin:$PATH
export LD_LIBRARY_PATH=/usr/lib/openmpi/lib:$LD_LIBRARY_PATH
