#!/bin/bash

# =============================================================================
# Authors:      Román García Guill
# Contact:      romangarciaguill@gmail.com
# Created:      Sun 24. May 2026
#
# Purpose:      Creates the whole tmux workspace for scientific reasearch.
# =============================================================================

SESSION="basic"

if ! tmux has-session -t "$SESSION" 2>/dev/null; then

    # Window 1: mail
    tmux new-session -d -s "$SESSION" -n mail
    tmux send-keys -t "$SESSION":mail 'aerc' C-m

    # Window 2: monitoring
    tmux new-window -t "$SESSION" -n news
    tmux send-keys -t "$SESSION":news 'news' C-m

    # Window 3: todo
    tmux new-window -t "$SESSION" -n todo
    tmux send-keys -t "$SESSION":todo 'vim ~/Notes/ToDo.md' C-m

    # Focus
    tmux select-window -t "$SESSION":mail

fi

exec tmux attach-session -t "$SESSION"
