# set terminal proper colors
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*:Tc"

# set mouse support
set -g mouse on

# set vim support
set -g mode-keys vi
set -g focus-events on

# improve scrollback
set -g history-limit 50000

# First number 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# custom
set -g status-position top
set -g bell-action any
set -g visual-bell on
set -g monitor-activity on

# bindings
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v
