#!/bin/bash

# =============================================================================
# Authors:      Román García Guill
# Contact:      romangarciaguill@gmail.com
# Created:      Sun 24. May 2026
#
# Purpose:      Creates the whole tmux workspace for scientific reasearch.
# =============================================================================

SESSION="chill"
tmux has-session -t $SESSION 2>dev/null

if [ $? -ne 0 ]; then
    # 1.  Create new session with mail
    tmux new-session -d -s $SESSION -n 'mail'

    # 2. Create a second widonw for nvim
    tmux new-window -d -s $SESSION -n 'monitoring'
    tmux split-window -h -t $SESSION -n 'monitoring'
    
    tmux send-keys -t $SESSION:'monitoring'.1 'btop' C-m
    tmux send-keys -t $SESSION:'monitoring'.2 'gowork && vim ToDo.md' C-m
    tmux send-keys -t $SESSION:'mail' 'aerc' C-m

    tmux select-window -t $SESSION:'mail'
fi

tmux attach-session -t $SESSION
